name: Integration Tests Workflow

on:
  push:
    branches: [main, benchmarking-branch]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, benchmarking-branch, jdk-8 ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Run Integration Tests
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest
    environment: azure-prod
    strategy:
      matrix:
        java-version: [8]  # Add JDK 8 support
        distribution: ['semeru', 'adopt']
        include:
          - test-command: mvn -B compile test -Dtest=*IntegrationTests
            token-secret: DATABRICKS_TOKEN
            use-thrift-client: 'false'
          - test-command: mvn -B compile test -Dtest=**/fakeservice/tests/MultiChunkExecutionIntegrationTests.java,**/fakeservice/tests/ConnectionIntegrationTests.java
            token-secret: THRIFT_DATABRICKS_TOKEN
            use-thrift-client: 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Integration Tests
        run: ${{ matrix.test-command }}
        env:
          DATABRICKS_TOKEN: ${{ secrets[matrix.token-secret] }}
          DATABRICKS_USER: ${{ secrets.DATABRICKS_USER }}
          USE_THRIFT_CLIENT: ${{ matrix.use-thrift-client }}